### ISSUE TITLE
Include hardware schematics 

### ISSUE THREAD

**Issue by eimparas** [filipmu/Raspberry-Pi-Battery-Power-Monitor#1]
while making a portable Rpi i stumbled upon this project from [Here](https://hackaday.io/project/188675-battery-power-system-for-raspberry-pi/details)

i saw the Custom Board - RPI Shutdown Interface schematics 
but How did you incorporated the INA226 in your design ? 
are u using high or low side measurement ? etc 

thanks in advace

**Comment by filipmu** [comment]
The schematic of overall power system and the Eaglecad files for the power on/off board can be found on Hackaday: [Battery Power System for Raspberry Pi](https://hackaday.io/project/188675/gallery#86913b8ea2ba7e0248ed677a163f5909)

I added this to the readme.

**Comment by filipmu** [comment]
See here for schematic - it's part of the hackaday project: https://hackaday.io/project/188675/gallery#86913b8ea2ba7e0248ed677a163f5909

**Comment by eimparas** [comment]
Thank you for including them in the readme ! 

Hackaday can sometimes be clunky to navigate imho so a direct link is appriciated !
